# version: '3.4'
services:
  db:
    container_name: db
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '${POSTGRES_PORT}:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - express-network
  server:
    container_name: server
    env_file:
      - .env
    restart: 'no'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
      # - ./uploads:/app/uploads
    networks:
      - express-network

  # mailcatcher:
  #   container_name: mailcatcher
  #   image: schickling/mailcatcher
  #   ports:
  #     - '1080:1080' # MailCatcher web interface
  #     - '1025:1025' # MailCatcher SMTP server
  #   networks:
  #     - express-network

networks:
  express-network:
    driver: bridge
